### ISSUE TITLE
Your configuration does not work

### ISSUE THREAD

**Issue by ghost** [munchicken/htaccess_creator#1]
If you enter on my webpage on a inexistent link, https://eum.netalab.tk/hola for example, you can see that it works, i have changed iframe tag by img tag on css and html code.

For example:
ErrorDocument 404 '<style> body{background-color: #000000} img{display: block; margin-left: auto; margin-right: auto; width:750px; height:600px; border:none} </style> <img src="https://http.cat/404"></img>

If you change this at your actual configuration:
ErrorDocument 404 '<style> body{background-color: #000000} iframe{display: block; margin-left: auto; margin-right: auto; width:750px; height:600px; border:none} </style> <iframe src="https://http.cat/404"></iframe>

It will charge a black webpage without the image, i have analyzed source code via webtools on firefox and does not charge nothing at iframe body and this is the problem, the iframe does not charge the img.

**Comment by munchicken** [comment]
I noticed problems with my webpage lately too.  I found the problem...  HttpCats has changed X-Frame-Options to Deny, which caused the iframe to break and caused the black web pages with no image.  Since the HttpCats are all images, I think your suggestion to change iframes to imgs is a good fix.  I will push an update tonight.
